### ISSUE TITLE
Make curryable

### ISSUE THREAD

**Issue by cdock1029** [jonschlinkert/object.pick#2]
Consider reversing the parameter order, so this function can be curried:

``` js

const pick = require('object.pick');

const fields = ['id', 'firstName', 'lastName', 'email']

const pickUserFields = curry(pick)(fields)

const user = db.getUser(...)

const myUserObj = pickUserFields(user)

```

**Comment by doowb** [comment]
Most of the implementations of `pick` that I've seen use this order. I would just make a [partial-right](https://github.com/jonschlinkert/partial-right) application:

``` js
var pick = require('object.pick');
var partial = require('partial-right');

var fields = ['id', 'firstName', 'lastName', 'email'];
var pickUserFields = partial(pick, fields);

var user = db.getUser(...);
var myUserObj = pickUserFields(user);
```

**Comment by jonschlinkert** [comment]
It would be fairly trivial to switch args automatically too, since one of the args either needs to be a string or array, and the other an object. shouldn't impact performance at all
